# este docker file es para versiones 5.6.40 
FROM debian:8

MAINTAINER Manuel Vázquez "manuel.vazquez.gonzalez@hotmail.com"

RUN apt update && \
	apt upgrade -y && \
	apt install ca-certificates apt-transport-https locales wget -y && \
	localedef -i es_ES -c -f UTF-8 -A /usr/share/locale/locale.alias es_ES.UTF-8
ENV LANG es_ES.utf8 
RUN wget -q https://packages.sury.org/php/apt.gpg -O- | apt-key add - && \ 
	echo "deb https://packages.sury.org/php/ jessie main" | tee /etc/apt/sources.list.d/php.list && \
	apt update && \
	apt install -y apache2 php5.6 php5.6-mysql php5.6-curl php5.6-gd php5.6-mbstring php5.6-xml php5.6-xmlrpc php5.6-soap php5.6-intl php5.6-zip 
RUN rm /var/www/html/index.html
COPY ./wordpress/ /var/www/html/
ENTRYPOINT ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]

